name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Github Release
        if: github.ref == '/refs/heads/master'
        uses: kbrashears5/github-action-release-maker@master
        with:
          VERSION: ${{ steps.package-version.outputs.current-version}}
          TOKEN: ${{ secrets.ACTIONS }}